name: build

on: [push,pull_request,workflow_dispatch]

jobs:
  Windows:
    name: ${{ matrix.config }} Windows ${{ matrix.arch }}
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
      
    - name: Download WinDeps
      run: Invoke-WebRequest -Uri https://github.com/MRVN-Radiant/MRVN-WinDeps/releases/download/v0.2/windeps.zip -OutFile windeps.zip
      shell: powershell
      
    - name: Extract WinDeps
      run: 7z x windeps.zip
  
    - name: Setup msvc
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup CMake
      run: cmake . -G "Ninja" -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build .
      
    - name: Download Install Deps
      run: Invoke-WebRequest -Uri https://github.com/MRVN-Radiant/MRVN-WinDeps/releases/download/v0.2/install.7z -OutFile install.7z
      shell: powershell
      
    - name: Extract Install Deps
      run: 7z x install.7z
      
    - name: Where am i
      run: ls

    - name: Generate Artifact Name
      run: echo "ARTIFACT_NAME=$(echo MRVN-Radiant_`date -u -Idate`_`git rev-parse --short HEAD`_Windows_${{ matrix.arch }})" >> $GITHUB_ENV
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: install/
        if-no-files-found: error

  Linux:
    name: ${{ matrix.config }} Linux ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]

    steps:
    - name: Install tools
      run: |
          sudo apt-get -qq update
          sudo apt-get -y install mesa-common-dev qtbase5-dev
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup CMake
      run: cmake . -G "Unix Makefiles"

    - name: Build
      run: |
        cmake --build .

    - name: Generate Artifact Name
      run: |
        echo "ARTIFACT_NAME=$(echo MRVN-Radiant_`date -u -Idate`_`git rev-parse --short HEAD`_Linux_${{ matrix.arch }})" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: install/
        if-no-files-found: error
