name: build

on: [push, workflow_dispatch]

jobs:
  windows-msys:
    name: ${{ matrix.config }} Windows ${{ matrix.arch }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x86_64]
        cc: [gcc]
        include:
          - arch: x86
            msystem: MINGW32
            prefix: mingw-w64-i686

          - arch: x86_64
            msystem: MINGW64
            prefix: mingw-w64-x86_64

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        install: ${{ matrix.prefix }}-gtk2 ${{ matrix.prefix }}-gtkglext ${{ matrix.prefix }}-gtk-engines ${{ matrix.prefix }}-gtk-engine-murrine svn git
        msystem: ${{ matrix.msystem }}
        path-type: minimal
        release: false
        update: false

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      run: |
        make MAKEFILE_CONF=msys2-Makefile.conf BUILD=release -j$(nproc) 
        wget https://www.dropbox.com/s/hcgkwzzmja3m6c0/netradiant-custom-extra-win.zip
        unzip -o netradiant-custom-extra-win.zip -d "install"

    - uses: actions/upload-artifact@v3
      with:
        name: Windows-${{ matrix.arch }}
        path: install/
        if-no-files-found: error

    - uses: actions/upload-artifact@v3
      with:
        name: warnings
        path: windows-warn*.log

  linux:
    name: ${{ matrix.config }} Linux ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]

    steps:
    - name: Install tools
      run: |
          sudo apt-get -qq update
          sudo apt-get -y install mesa-common-dev libgtk2.0-dev libpango1.0-dev libgtkglext1-dev
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: |
        make -j 4 CXXFLAGS="-Wno-deprecated-declarations"

    - uses: actions/upload-artifact@v3
      with:
        name: Linux-${{ matrix.arch }}
        path: install/
        if-no-files-found: error
